export const pets = [
  {
    id: "1",
    name: "Luna",
    breed: "Golden Retriever",
    type: "Dog",
    age: "2 years",
    ageCategory: "young",
    gender: "Female",
    size: "Large",
    location: "San Francisco, CA",
    image:
      "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=300&fit=crop&crop=face",
    traits: ["Friendly", "Trained", "Good with kids"],
    urgent: false,
    description:
      "Luna is a beautiful Golden Retriever with a heart of gold. She's great with children and other pets, and loves to play fetch in the park. Luna is fully house-trained and knows several commands. She's looking for an active family who can give her plenty of exercise and love.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$250",
  },
  {
    id: "2",
    name: "Whiskers",
    breed: "Maine Coon",
    type: "Cat",
    age: "3 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Medium",
    location: "Los Angeles, CA",
    image:
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=300&fit=crop&crop=face",
    traits: ["Calm", "Indoor", "Affectionate"],
    urgent: true,
    description:
      "Whiskers is a gorgeous Maine Coon with a luxurious coat and gentle personality. He enjoys lounging in sunny spots and being petted. Whiskers is litter-trained and would do best in a quiet home where he can be the center of attention.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$150",
  },
  {
    id: "3",
    name: "Buddy",
    breed: "Labrador Mix",
    type: "Dog",
    age: "1 year",
    ageCategory: "young",
    gender: "Male",
    size: "Large",
    location: "New York, NY",
    image:
      "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=300&fit=crop&crop=face",
    traits: ["Energetic", "Playful", "Loyal"],
    urgent: false,
    description:
      "Buddy is a playful Labrador mix who loves to run and play. He's still learning basic commands but is very eager to please. Buddy would thrive in an active household with a yard where he can burn off energy. He gets along well with other dogs but hasn't been tested with cats.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$200",
  },
  {
    id: "4",
    name: "Mittens",
    breed: "Domestic Shorthair",
    type: "Cat",
    age: "5 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Small",
    location: "Chicago, IL",
    image:
      "https://images.unsplash.com/photo-1513245543132-31f507417b26?w=400&h=300&fit=crop&crop=face",
    traits: ["Independent", "Quiet", "Good with cats"],
    urgent: false,
    description:
      "Mittens is a sweet, independent cat who enjoys her alone time but will seek out affection on her terms. She's very clean and would do well in an apartment. Mittens gets along with other cats but prefers a home without dogs or small children.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$100",
  },
  {
    id: "5",
    name: "Max",
    breed: "German Shepherd",
    type: "Dog",
    age: "4 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Large",
    location: "Austin, TX",
    image:
      "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400&h=300&fit=crop&crop=face",
    traits: ["Intelligent", "Protective", "Trained"],
    urgent: false,
    description:
      "Max is a well-trained German Shepherd with excellent manners. He's protective of his family but friendly once he gets to know you. Max would do best in a home with experienced dog owners who understand the breed. He needs regular exercise and mental stimulation.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$300",
  },
  {
    id: "6",
    name: "Daisy",
    breed: "Beagle",
    type: "Dog",
    age: "6 months",
    ageCategory: "baby",
    gender: "Female",
    size: "Small",
    location: "Seattle, WA",
    image:
      "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=400&h=300&fit=crop&crop=face",
    traits: ["Curious", "Playful", "Good with dogs"],
    urgent: true,
    description:
      "Daisy is an adorable Beagle puppy full of energy and curiosity. She's still learning basic commands and house-training. Daisy would do well in a home with a patient family willing to continue her training. She loves other dogs and would benefit from having a canine companion.",
    healthInfo: "Vaccinated, microchipped, will be spayed at appropriate age",
    adoptionFee: "$275",
  },
  {
    id: "7",
    name: "Oliver",
    breed: "Siamese",
    type: "Cat",
    age: "2 years",
    ageCategory: "young",
    gender: "Male",
    size: "Medium",
    location: "Denver, CO",
    image:
      "https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=400&h=300&fit=crop&crop=face",
    traits: ["Vocal", "Intelligent", "Affectionate"],
    urgent: false,
    description:
      "Oliver is a chatty Siamese cat who loves to tell you about his day. He's very intelligent and can learn tricks quickly. Oliver enjoys interactive toys and would do well in a home where he gets plenty of attention and playtime. He's good with respectful children and other cats.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$175",
  },
  {
    id: "8",
    name: "Rocky",
    breed: "Pit Bull Mix",
    type: "Dog",
    age: "7 years",
    ageCategory: "senior",
    gender: "Male",
    size: "Medium",
    location: "Miami, FL",
    image:
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=300&fit=crop&crop=face",
    traits: ["Gentle", "Loyal", "House trained"],
    urgent: true,
    description:
      "Rocky is a sweet senior dog looking for a quiet home to spend his golden years. Despite his age, he still enjoys short walks and plenty of cuddle time. Rocky is fully house-trained and has excellent manners. He would do best in a home without young children or other pets.",
    healthInfo: "Neutered, vaccinated, microchipped, dental work completed",
    adoptionFee: "$150",
  },
  {
    id: "9",
    name: "Coco",
    breed: "Ragdoll",
    type: "Cat",
    age: "1 year",
    ageCategory: "young",
    gender: "Female",
    size: "Medium",
    location: "Portland, OR",
    image:
      "https://images.unsplash.com/photo-1573824267776-8b0e5d3e3d3e?w=400&h=300&fit=crop&crop=face",
    traits: ["Gentle", "Affectionate", "Good with kids"],
    urgent: false,
    description:
      "Coco is a beautiful Ragdoll cat known for her docile and affectionate nature. She loves to be held and will follow you around the house. Coco is good with children and other pets, making her a perfect family cat. She's litter-trained and enjoys interactive toys.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$200",
  },
  {
    id: "10",
    name: "Charlie",
    breed: "Dachshund",
    type: "Dog",
    age: "3 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Small",
    location: "Boston, MA",
    image:
      "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400&h=300&fit=crop&crop=face",
    traits: ["Loyal", "Curious", "House trained"],
    urgent: false,
    description:
      "Charlie is a charming Dachshund with a big personality in a small package. He's very loyal to his people and enjoys snuggling under blankets. Charlie is house-trained and knows basic commands. He would do best in a home with no small children and preferably as the only pet.",
    healthInfo: "Neutered, vaccinated, microchipped, dental cleaning completed",
    adoptionFee: "$225",
  },
  {
    id: "11",
    name: "Bella",
    breed: "Siberian Husky",
    type: "Dog",
    age: "2 years",
    ageCategory: "young",
    gender: "Female",
    size: "Large",
    location: "Minneapolis, MN",
    image:
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=400&h=300&fit=crop&crop=face",
    traits: ["Energetic", "Intelligent", "Vocal"],
    urgent: false,
    description:
      "Bella is a stunning Siberian Husky with boundless energy and a playful spirit. She needs an active family who can provide plenty of exercise and mental stimulation. Bella is partially trained but would benefit from continued training. She gets along with other dogs but has a high prey drive for smaller animals.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$275",
  },
  {
    id: "12",
    name: "Simba",
    breed: "Orange Tabby",
    type: "Cat",
    age: "8 years",
    ageCategory: "senior",
    gender: "Male",
    size: "Large",
    location: "Philadelphia, PA",
    image:
      "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400&h=300&fit=crop&crop=face",
    traits: ["Lazy", "Affectionate", "Good with cats"],
    urgent: true,
    description:
      "Simba is a laid-back senior cat who enjoys lounging in sunny spots and receiving gentle pets. He's very low-maintenance and would do well in a quiet home. Simba gets along with other calm cats but would prefer a home without dogs or young children. He's looking for a peaceful retirement home.",
    healthInfo:
      "Neutered, vaccinated, microchipped, senior bloodwork completed",
    adoptionFee: "$75",
  },
  {
    id: "13",
    name: "Ruby",
    breed: "Border Collie",
    type: "Dog",
    age: "3 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Medium",
    location: "Phoenix, AZ",
    image:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=300&fit=crop&crop=face",
    traits: ["Intelligent", "Active", "Trained"],
    urgent: false,
    description:
      "Ruby is an incredibly smart Border Collie who loves mental challenges and physical activity. She knows many commands and tricks, and would excel in agility training. Ruby needs an experienced owner who can provide her with plenty of mental stimulation and exercise. She's great with older children but may try to herd smaller kids.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$280",
  },
  {
    id: "14",
    name: "Shadow",
    breed: "Black Cat Mix",
    type: "Cat",
    age: "4 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Medium",
    location: "Nashville, TN",
    image:
      "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400&h=300&fit=crop&crop=face",
    traits: ["Mysterious", "Independent", "Night owl"],
    urgent: false,
    description:
      "Shadow is a sleek black cat with striking yellow eyes. He's independent but enjoys quiet companionship. Shadow is most active in the evenings and loves to watch birds from windows. He would do well in a calm household and gets along with other cats after proper introduction.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$125",
  },
  {
    id: "15",
    name: "Milo",
    breed: "French Bulldog",
    type: "Dog",
    age: "5 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Small",
    location: "Las Vegas, NV",
    image:
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=300&fit=crop&crop=face",
    traits: ["Calm", "Friendly", "Good with kids"],
    urgent: false,
    description:
      "Milo is a sweet French Bulldog with a calm demeanor and loving personality. He enjoys short walks and lots of cuddle time. Milo is great with children and other dogs, making him a perfect family companion. He's house-trained and has excellent manners indoors.",
    healthInfo: "Neutered, vaccinated, microchipped, breathing checked",
    adoptionFee: "$350",
  },
  {
    id: "16",
    name: "Princess",
    breed: "Persian",
    type: "Cat",
    age: "6 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Medium",
    location: "Atlanta, GA",
    image:
      "https://images.unsplash.com/photo-1571566882372-1598d88abd90?w=400&h=300&fit=crop&crop=face",
    traits: ["Regal", "Quiet", "Indoor"],
    urgent: true,
    description:
      "Princess is a beautiful Persian cat with a luxurious long coat. She's quiet and dignified, preferring a peaceful environment. Princess requires daily grooming to maintain her beautiful coat and would do best with an experienced cat owner. She's litter-trained and prefers to be the only pet.",
    healthInfo: "Spayed, vaccinated, microchipped, dental work completed",
    adoptionFee: "$200",
  },
  {
    id: "17",
    name: "Zeus",
    breed: "Great Dane",
    type: "Dog",
    age: "3 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Large",
    location: "Dallas, TX",
    image:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=300&fit=crop&crop=face",
    traits: ["Gentle giant", "Calm", "Good with kids"],
    urgent: false,
    description:
      "Zeus is a gentle Great Dane who thinks he's a lap dog despite his impressive size. He's incredibly gentle with children and has a calm, patient temperament. Zeus is house-trained and walks well on a leash. He would do best in a home with a large yard and owners who understand giant breed needs.",
    healthInfo: "Neutered, vaccinated, microchipped, joint supplements",
    adoptionFee: "$400",
  },
  {
    id: "18",
    name: "Patches",
    breed: "Calico",
    type: "Cat",
    age: "2 years",
    ageCategory: "young",
    gender: "Female",
    size: "Small",
    location: "San Diego, CA",
    image:
      "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=300&fit=crop&crop=face",
    traits: ["Playful", "Colorful", "Social"],
    urgent: false,
    description:
      "Patches is a beautiful calico cat with a vibrant personality to match her colorful coat. She's playful and social, enjoying interactive toys and games. Patches gets along well with other cats and would thrive in a home where she gets plenty of attention and playtime.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$140",
  },
  {
    id: "19",
    name: "Scout",
    breed: "Australian Shepherd",
    type: "Dog",
    age: "1 year",
    ageCategory: "young",
    gender: "Male",
    size: "Medium",
    location: "Colorado Springs, CO",
    image:
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=400&h=300&fit=crop&crop=face",
    traits: ["Energetic", "Smart", "Loyal"],
    urgent: false,
    description:
      "Scout is a young Australian Shepherd with boundless energy and intelligence. He's eager to learn and would excel in training classes or dog sports. Scout needs an active family who can provide him with plenty of physical and mental exercise. He's great with older children and other dogs.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$290",
  },
  {
    id: "20",
    name: "Duchess",
    breed: "Russian Blue",
    type: "Cat",
    age: "4 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Medium",
    location: "Richmond, VA",
    image:
      "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=300&fit=crop&crop=face",
    traits: ["Elegant", "Reserved", "Intelligent"],
    urgent: false,
    description:
      "Duchess is an elegant Russian Blue with a reserved but loving personality. She's intelligent and observant, preferring to watch and assess before engaging. Duchess would do well in a quiet home with patient owners who will let her warm up at her own pace. She's litter-trained and very clean.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$180",
  },
];
