export const pets = [
  {
    id: "1",
    name: "Luna",
    breed: "Golden Retriever",
    type: "Dog",
    age: "2 years",
    ageCategory: "young",
    gender: "Female",
    size: "Large",
    location: "San Francisco, CA",
    image: "https://source.unsplash.com/400x300/?golden-retriever",
    traits: ["Friendly", "Trained", "Good with kids"],
    urgent: false,
    description:
      "Luna is a beautiful Golden Retriever with a heart of gold. She's great with children and other pets, and loves to play fetch in the park. Luna is fully house-trained and knows several commands. She's looking for an active family who can give her plenty of exercise and love.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$250",
  },
  {
    id: "2",
    name: "Whiskers",
    breed: "Maine Coon",
    type: "Cat",
    age: "3 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Medium",
    location: "Los Angeles, CA",
    image: "https://source.unsplash.com/400x300/?maine-coon",
    traits: ["Calm", "Indoor", "Affectionate"],
    urgent: true,
    description:
      "Whiskers is a gorgeous Maine Coon with a luxurious coat and gentle personality. He enjoys lounging in sunny spots and being petted. Whiskers is litter-trained and would do best in a quiet home where he can be the center of attention.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$150",
  },
  {
    id: "3",
    name: "Buddy",
    breed: "Labrador Mix",
    type: "Dog",
    age: "1 year",
    ageCategory: "young",
    gender: "Male",
    size: "Large",
    location: "New York, NY",
    image: "https://source.unsplash.com/400x300/?labrador",
    traits: ["Energetic", "Playful", "Loyal"],
    urgent: false,
    description:
      "Buddy is a playful Labrador mix who loves to run and play. He's still learning basic commands but is very eager to please. Buddy would thrive in an active household with a yard where he can burn off energy. He gets along well with other dogs but hasn't been tested with cats.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$200",
  },
  {
    id: "4",
    name: "Mittens",
    breed: "Domestic Shorthair",
    type: "Cat",
    age: "5 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Small",
    location: "Chicago, IL",
    image: "https://source.unsplash.com/400x300/?domestic-cat",
    traits: ["Independent", "Quiet", "Good with cats"],
    urgent: false,
    description:
      "Mittens is a sweet, independent cat who enjoys her alone time but will seek out affection on her terms. She's very clean and would do well in an apartment. Mittens gets along with other cats but prefers a home without dogs or small children.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$100",
  },
  {
    id: "5",
    name: "Max",
    breed: "German Shepherd",
    type: "Dog",
    age: "4 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Large",
    location: "Austin, TX",
    image: "https://source.unsplash.com/400x300/?german-shepherd",
    traits: ["Intelligent", "Protective", "Trained"],
    urgent: false,
    description:
      "Max is a well-trained German Shepherd with excellent manners. He's protective of his family but friendly once he gets to know you. Max would do best in a home with experienced dog owners who understand the breed. He needs regular exercise and mental stimulation.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$300",
  },
  {
    id: "6",
    name: "Daisy",
    breed: "Beagle",
    type: "Dog",
    age: "6 months",
    ageCategory: "baby",
    gender: "Female",
    size: "Small",
    location: "Seattle, WA",
    image: "https://source.unsplash.com/400x300/?beagle-puppy",
    traits: ["Curious", "Playful", "Good with dogs"],
    urgent: true,
    description:
      "Daisy is an adorable Beagle puppy full of energy and curiosity. She's still learning basic commands and house-training. Daisy would do well in a home with a patient family willing to continue her training. She loves other dogs and would benefit from having a canine companion.",
    healthInfo: "Vaccinated, microchipped, will be spayed at appropriate age",
    adoptionFee: "$275",
  },
  {
    id: "7",
    name: "Oliver",
    breed: "Siamese",
    type: "Cat",
    age: "2 years",
    ageCategory: "young",
    gender: "Male",
    size: "Medium",
    location: "Denver, CO",
    image: "https://source.unsplash.com/400x300/?siamese-cat",
    traits: ["Vocal", "Intelligent", "Affectionate"],
    urgent: false,
    description:
      "Oliver is a chatty Siamese cat who loves to tell you about his day. He's very intelligent and can learn tricks quickly. Oliver enjoys interactive toys and would do well in a home where he gets plenty of attention and playtime. He's good with respectful children and other cats.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$175",
  },
  {
    id: "8",
    name: "Rocky",
    breed: "Pit Bull Mix",
    type: "Dog",
    age: "7 years",
    ageCategory: "senior",
    gender: "Male",
    size: "Medium",
    location: "Miami, FL",
    image: "https://source.unsplash.com/400x300/?pitbull",
    traits: ["Gentle", "Loyal", "House trained"],
    urgent: true,
    description:
      "Rocky is a sweet senior dog looking for a quiet home to spend his golden years. Despite his age, he still enjoys short walks and plenty of cuddle time. Rocky is fully house-trained and has excellent manners. He would do best in a home without young children or other pets.",
    healthInfo: "Neutered, vaccinated, microchipped, dental work completed",
    adoptionFee: "$150",
  },
  {
    id: "9",
    name: "Coco",
    breed: "Ragdoll",
    type: "Cat",
    age: "1 year",
    ageCategory: "young",
    gender: "Female",
    size: "Medium",
    location: "Portland, OR",
    image: "https://source.unsplash.com/400x300/?ragdoll-cat",
    traits: ["Gentle", "Affectionate", "Good with kids"],
    urgent: false,
    description:
      "Coco is a beautiful Ragdoll cat known for her docile and affectionate nature. She loves to be held and will follow you around the house. Coco is good with children and other pets, making her a perfect family cat. She's litter-trained and enjoys interactive toys.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$200",
  },
  {
    id: "10",
    name: "Charlie",
    breed: "Dachshund",
    type: "Dog",
    age: "3 years",
    ageCategory: "adult",
    gender: "Male",
    size: "Small",
    location: "Boston, MA",
    image: "https://source.unsplash.com/400x300/?dachshund",
    traits: ["Loyal", "Curious", "House trained"],
    urgent: false,
    description:
      "Charlie is a charming Dachshund with a big personality in a small package. He's very loyal to his people and enjoys snuggling under blankets. Charlie is house-trained and knows basic commands. He would do best in a home with no small children and preferably as the only pet.",
    healthInfo: "Neutered, vaccinated, microchipped, dental cleaning completed",
    adoptionFee: "$225",
  },
  {
    id: "11",
    name: "Bella",
    breed: "Siberian Husky",
    type: "Dog",
    age: "2 years",
    ageCategory: "young",
    gender: "Female",
    size: "Large",
    location: "Minneapolis, MN",
    image: "https://source.unsplash.com/400x300/?siberian-husky",
    traits: ["Energetic", "Intelligent", "Vocal"],
    urgent: false,
    description:
      "Bella is a stunning Siberian Husky with boundless energy and a playful spirit. She needs an active family who can provide plenty of exercise and mental stimulation. Bella is partially trained but would benefit from continued training. She gets along with other dogs but has a high prey drive for smaller animals.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$275",
  },
  {
    id: "12",
    name: "Simba",
    breed: "Orange Tabby",
    type: "Cat",
    age: "8 years",
    ageCategory: "senior",
    gender: "Male",
    size: "Large",
    location: "Philadelphia, PA",
    image: "https://source.unsplash.com/400x300/?orange-tabby-cat",
    traits: ["Lazy", "Affectionate", "Good with cats"],
    urgent: true,
    description:
      "Simba is a laid-back senior cat who enjoys lounging in sunny spots and receiving gentle pets. He's very low-maintenance and would do well in a quiet home. Simba gets along with other calm cats but would prefer a home without dogs or young children. He's looking for a peaceful retirement home.",
    healthInfo:
      "Neutered, vaccinated, microchipped, senior bloodwork completed",
    adoptionFee: "$75",
  },
  // New entries below:
  {
    id: "13",
    name: "Pepper",
    breed: "French Bulldog",
    type: "Dog",
    age: "3 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Small",
    location: "Houston, TX",
    image: "https://source.unsplash.com/400x300/?french-bulldog",
    traits: ["Affectionate", "Quiet", "Apartment-friendly"],
    urgent: false,
    description:
      "Pepper is a sweet Frenchie who loves cuddles and short walks. She’s well-mannered and perfect for apartment living. Pepper gets along great with calm dogs and older kids.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$275",
  },
  {
    id: "14",
    name: "Zephyr",
    breed: "Border Collie",
    type: "Dog",
    age: "2 years",
    ageCategory: "young",
    gender: "Male",
    size: "Medium",
    location: "Boulder, CO",
    image: "https://source.unsplash.com/400x300/?border-collie",
    traits: ["Energetic", "Smart", "Agility-trained"],
    urgent: false,
    description:
      "Zephyr is a high-energy Border Collie who thrives on activity and mental challenges. He knows basic agility commands and would be an awesome partner for active owners into sports or outdoor adventures.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$325",
  },
  {
    id: "15",
    name: "Nimbus",
    breed: "Persian",
    type: "Cat",
    age: "4 years",
    ageCategory: "adult",
    gender: "Female",
    size: "Medium",
    location: "Phoenix, AZ",
    image: "https://source.unsplash.com/400x300/?persian-cat",
    traits: ["Calm", "Fluffy", "Lap-cat"],
    urgent: false,
    description:
      "Nimbus is a plush Persian cat who loves lounging on your lap. She prefers quiet environments and gentle pets. Her luxurious coat and serene nature make her ideal for a relaxed home.",
    healthInfo: "Spayed, vaccinated, microchipped",
    adoptionFee: "$200",
  },
  {
    id: "16",
    name: "Echo",
    breed: "Australian Shepherd",
    type: "Dog",
    age: "5 months",
    ageCategory: "baby",
    gender: "Male",
    size: "Medium",
    location: "San Diego, CA",
    image: "https://source.unsplash.com/400x300/?australian-shepherd-puppy",
    traits: ["Playful", "Herding instincts", "Trainable"],
    urgent: true,
    description:
      "Echo is an active Aussie pup bursting with energy and eager to learn. He’ll need a family ready for puppy training and plenty of exercise—fenced yard recommended!",
    healthInfo: "Vaccinated, microchipped, will be neutered",
    adoptionFee: "$300",
  },
  {
    id: "17",
    name: "Gizmo",
    breed: "Scottish Fold",
    type: "Cat",
    age: "1 year",
    ageCategory: "young",
    gender: "Male",
    size: "Small",
    location: "Atlanta, GA",
    image: "https://source.unsplash.com/400x300/?scottish-fold-cat",
    traits: ["Affectionate", "Folded ears", "Quiet"],
    urgent: false,
    description:
      "Gizmo is a charming Scottish Fold known for his sweet temperament and velvety folded ears. He’s affectionate and gentle—great for quieter households or senior families.",
    healthInfo: "Neutered, vaccinated, microchipped",
    adoptionFee: "$225",
  },
  {
    id: "18",
    name: "Rusty",
    breed: "Cocker Spaniel",
    type: "Dog",
    age: "6 years",
    ageCategory: "senior",
    gender: "Male",
    size: "Medium",
    location: "Tampa, FL",
    image: "https://source.unsplash.com/400x300/?cocker-spaniel",
    traits: ["Gentle", "Good with kids", "Low energy"],
    urgent: false,
    description:
      "Rusty is a gentle Cocker Spaniel who loves lounging and easy walks. He’s great with children and would be perfect for a loving, calm home where he can spend his golden years in comfort.",
    healthInfo: "Neutered, vaccinated, microchipped, dental work completed",
    adoptionFee: "$175",
  },
];
